/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : string,
  'body' : string,
  'authorName' : string,
  'createdDate' : string,
  'classId' : string,
}
export interface Assignment {
  'id' : string,
  'title' : string,
  'maxScore' : bigint,
  'createdDate' : string,
  'dueDate' : string,
  'description' : string,
  'classId' : string,
}
export interface AttendanceRecord {
  'id' : string,
  'status' : AttendanceStatus,
  'studentId' : string,
  'date' : string,
  'classId' : string,
}
export type AttendanceStatus = { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export interface Class {
  'id' : string,
  'subject' : string,
  'name' : string,
  'section' : string,
  'studentIds' : Array<string>,
}
export interface Grade {
  'id' : string,
  'studentId' : string,
  'feedback' : string,
  'score' : bigint,
  'assignmentId' : string,
}
export interface Message {
  'id' : string,
  'sentDate' : string,
  'subject' : string,
  'body' : string,
  'isRead' : boolean,
  'senderName' : string,
  'recipientName' : string,
  'recipientId' : string,
  'senderId' : string,
}
export interface ScheduleEntry {
  'id' : string,
  'startTime' : string,
  'subject' : string,
  'endTime' : string,
  'dayOfWeek' : bigint,
  'classId' : string,
  'roomNumber' : string,
  'periodNumber' : bigint,
}
export interface Student {
  'id' : string,
  'enrolledDate' : string,
  'name' : string,
  'photoUrl' : string,
  'classId' : string,
  'email' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addAnnouncement' : ActorMethod<[string, string, string, string], string>,
  'addAssignment' : ActorMethod<
    [string, string, string, string, bigint],
    string
  >,
  'addClass' : ActorMethod<[string, string, string], string>,
  'addScheduleEntry' : ActorMethod<
    [bigint, bigint, string, string, string, string, string],
    string
  >,
  'addStudent' : ActorMethod<[string, string, string, string, string], string>,
  'deleteAnnouncement' : ActorMethod<[string], boolean>,
  'deleteAssignment' : ActorMethod<[string], boolean>,
  'deleteClass' : ActorMethod<[string], boolean>,
  'deleteScheduleEntry' : ActorMethod<[string], boolean>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAssignmentsByClass' : ActorMethod<[string], Array<Assignment>>,
  'getAttendanceByClassAndDate' : ActorMethod<
    [string, string],
    Array<AttendanceRecord>
  >,
  'getAttendanceByStudent' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getClassById' : ActorMethod<[string], Class>,
  'getClasses' : ActorMethod<[], Array<Class>>,
  'getClassesSortedById' : ActorMethod<[], Array<Class>>,
  'getGradesByAssignment' : ActorMethod<[string], Array<Grade>>,
  'getGradesByStudent' : ActorMethod<[string], Array<Grade>>,
  'getMessageThread' : ActorMethod<[string, string], Array<Message>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getSchedule' : ActorMethod<[], Array<ScheduleEntry>>,
  'getScheduleByDay' : ActorMethod<[bigint], Array<ScheduleEntry>>,
  'getStudentById' : ActorMethod<[string], Student>,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getStudentsByClass' : ActorMethod<[string], Array<Student>>,
  'getUnreadCount' : ActorMethod<[string], bigint>,
  'markAttendance' : ActorMethod<
    [string, string, string, AttendanceStatus],
    string
  >,
  'markMessageRead' : ActorMethod<[string], boolean>,
  'recordGrade' : ActorMethod<[string, string, bigint, string], string>,
  'removeStudent' : ActorMethod<[string], boolean>,
  'sendMessage' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'updateAssignment' : ActorMethod<[Assignment], boolean>,
  'updateAttendance' : ActorMethod<[AttendanceRecord], boolean>,
  'updateClass' : ActorMethod<[Class], boolean>,
  'updateGrade' : ActorMethod<[Grade], boolean>,
  'updateScheduleEntry' : ActorMethod<[ScheduleEntry], boolean>,
  'updateStudent' : ActorMethod<[Student], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];