/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'authorName' : IDL.Text,
  'createdDate' : IDL.Text,
  'classId' : IDL.Text,
});
export const Assignment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'maxScore' : IDL.Nat,
  'createdDate' : IDL.Text,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'classId' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : AttendanceStatus,
  'studentId' : IDL.Text,
  'date' : IDL.Text,
  'classId' : IDL.Text,
});
export const Class = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'studentIds' : IDL.Vec(IDL.Text),
});
export const Grade = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'assignmentId' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'sentDate' : IDL.Text,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'isRead' : IDL.Bool,
  'senderName' : IDL.Text,
  'recipientName' : IDL.Text,
  'recipientId' : IDL.Text,
  'senderId' : IDL.Text,
});
export const ScheduleEntry = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Text,
  'subject' : IDL.Text,
  'endTime' : IDL.Text,
  'dayOfWeek' : IDL.Nat,
  'classId' : IDL.Text,
  'roomNumber' : IDL.Text,
  'periodNumber' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'enrolledDate' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'classId' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addAssignment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'addClass' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'addScheduleEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteAssignment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteClass' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteScheduleEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAssignmentsByClass' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getAttendanceByClassAndDate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getClassById' : IDL.Func([IDL.Text], [Class], ['query']),
  'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getClassesSortedById' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getGradesByAssignment' : IDL.Func([IDL.Text], [IDL.Vec(Grade)], ['query']),
  'getGradesByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Grade)], ['query']),
  'getMessageThread' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getSchedule' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
  'getScheduleByDay' : IDL.Func([IDL.Nat], [IDL.Vec(ScheduleEntry)], ['query']),
  'getStudentById' : IDL.Func([IDL.Text], [Student], ['query']),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getStudentsByClass' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AttendanceStatus],
      [IDL.Text],
      [],
    ),
  'markMessageRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'recordGrade' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'removeStudent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateAssignment' : IDL.Func([Assignment], [IDL.Bool], []),
  'updateAttendance' : IDL.Func([AttendanceRecord], [IDL.Bool], []),
  'updateClass' : IDL.Func([Class], [IDL.Bool], []),
  'updateGrade' : IDL.Func([Grade], [IDL.Bool], []),
  'updateScheduleEntry' : IDL.Func([ScheduleEntry], [IDL.Bool], []),
  'updateStudent' : IDL.Func([Student], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'authorName' : IDL.Text,
    'createdDate' : IDL.Text,
    'classId' : IDL.Text,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'maxScore' : IDL.Nat,
    'createdDate' : IDL.Text,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'classId' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : AttendanceStatus,
    'studentId' : IDL.Text,
    'date' : IDL.Text,
    'classId' : IDL.Text,
  });
  const Class = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'studentIds' : IDL.Vec(IDL.Text),
  });
  const Grade = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'assignmentId' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'sentDate' : IDL.Text,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'isRead' : IDL.Bool,
    'senderName' : IDL.Text,
    'recipientName' : IDL.Text,
    'recipientId' : IDL.Text,
    'senderId' : IDL.Text,
  });
  const ScheduleEntry = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Text,
    'subject' : IDL.Text,
    'endTime' : IDL.Text,
    'dayOfWeek' : IDL.Nat,
    'classId' : IDL.Text,
    'roomNumber' : IDL.Text,
    'periodNumber' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'enrolledDate' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'classId' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addAssignment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'addClass' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'addScheduleEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteAssignment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteClass' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteScheduleEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAssignmentsByClass' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getAttendanceByClassAndDate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getClassById' : IDL.Func([IDL.Text], [Class], ['query']),
    'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getClassesSortedById' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getGradesByAssignment' : IDL.Func([IDL.Text], [IDL.Vec(Grade)], ['query']),
    'getGradesByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Grade)], ['query']),
    'getMessageThread' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getSchedule' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
    'getScheduleByDay' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ScheduleEntry)],
        ['query'],
      ),
    'getStudentById' : IDL.Func([IDL.Text], [Student], ['query']),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getStudentsByClass' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, AttendanceStatus],
        [IDL.Text],
        [],
      ),
    'markMessageRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'recordGrade' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'removeStudent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateAssignment' : IDL.Func([Assignment], [IDL.Bool], []),
    'updateAttendance' : IDL.Func([AttendanceRecord], [IDL.Bool], []),
    'updateClass' : IDL.Func([Class], [IDL.Bool], []),
    'updateGrade' : IDL.Func([Grade], [IDL.Bool], []),
    'updateScheduleEntry' : IDL.Func([ScheduleEntry], [IDL.Bool], []),
    'updateStudent' : IDL.Func([Student], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };