/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Grade {
    id: string;
    studentId: string;
    feedback: string;
    score: bigint;
    assignmentId: string;
}
export interface Class {
    id: string;
    subject: string;
    name: string;
    section: string;
    studentIds: Array<string>;
}
export interface ScheduleEntry {
    id: string;
    startTime: string;
    subject: string;
    endTime: string;
    dayOfWeek: bigint;
    classId: string;
    roomNumber: string;
    periodNumber: bigint;
}
export interface Message {
    id: string;
    sentDate: string;
    subject: string;
    body: string;
    isRead: boolean;
    senderName: string;
    recipientName: string;
    recipientId: string;
    senderId: string;
}
export interface Assignment {
    id: string;
    title: string;
    maxScore: bigint;
    createdDate: string;
    dueDate: string;
    description: string;
    classId: string;
}
export interface AttendanceRecord {
    id: string;
    status: AttendanceStatus;
    studentId: string;
    date: string;
    classId: string;
}
export interface Announcement {
    id: string;
    title: string;
    body: string;
    authorName: string;
    createdDate: string;
    classId: string;
}
export interface Student {
    id: string;
    enrolledDate: string;
    name: string;
    photoUrl: string;
    classId: string;
    email: string;
    phone: string;
}
export enum AttendanceStatus {
    present = "present",
    late = "late",
    absent = "absent"
}
export interface backendInterface {
    addAnnouncement(title: string, body: string, classId: string, authorName: string): Promise<string>;
    addAssignment(title: string, description: string, classId: string, dueDate: string, maxScore: bigint): Promise<string>;
    addClass(name: string, subject: string, section: string): Promise<string>;
    addScheduleEntry(dayOfWeek: bigint, periodNumber: bigint, subject: string, classId: string, startTime: string, endTime: string, roomNumber: string): Promise<string>;
    addStudent(name: string, email: string, phone: string, classId: string, photoUrl: string): Promise<string>;
    deleteAnnouncement(announcementId: string): Promise<boolean>;
    deleteAssignment(assignmentId: string): Promise<boolean>;
    deleteClass(classId: string): Promise<boolean>;
    deleteScheduleEntry(scheduleId: string): Promise<boolean>;
    getAnnouncements(): Promise<Array<Announcement>>;
    getAssignments(): Promise<Array<Assignment>>;
    getAssignmentsByClass(classId: string): Promise<Array<Assignment>>;
    getAttendanceByClassAndDate(classId: string, date: string): Promise<Array<AttendanceRecord>>;
    getAttendanceByStudent(studentId: string): Promise<Array<AttendanceRecord>>;
    getClassById(classId: string): Promise<Class>;
    getClasses(): Promise<Array<Class>>;
    getClassesSortedById(): Promise<Array<Class>>;
    getGradesByAssignment(assignmentId: string): Promise<Array<Grade>>;
    getGradesByStudent(studentId: string): Promise<Array<Grade>>;
    getMessageThread(userId: string, otherUserId: string): Promise<Array<Message>>;
    getMessages(userId: string): Promise<Array<Message>>;
    getSchedule(): Promise<Array<ScheduleEntry>>;
    getScheduleByDay(dayOfWeek: bigint): Promise<Array<ScheduleEntry>>;
    getStudentById(studentId: string): Promise<Student>;
    getStudents(): Promise<Array<Student>>;
    getStudentsByClass(classId: string): Promise<Array<Student>>;
    getUnreadCount(userId: string): Promise<bigint>;
    markAttendance(studentId: string, classId: string, date: string, status: AttendanceStatus): Promise<string>;
    markMessageRead(messageId: string): Promise<boolean>;
    recordGrade(studentId: string, assignmentId: string, score: bigint, feedback: string): Promise<string>;
    removeStudent(studentId: string): Promise<boolean>;
    sendMessage(senderId: string, senderName: string, recipientId: string, recipientName: string, subject: string, body: string): Promise<string>;
    updateAssignment(updatedAssignment: Assignment): Promise<boolean>;
    updateAttendance(updatedRecord: AttendanceRecord): Promise<boolean>;
    updateClass(updatedClass: Class): Promise<boolean>;
    updateGrade(updatedGrade: Grade): Promise<boolean>;
    updateScheduleEntry(updatedEntry: ScheduleEntry): Promise<boolean>;
    updateStudent(updatedStudent: Student): Promise<boolean>;
}
import type { AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAnnouncement(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addAssignment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAssignment(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAssignment(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addClass(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addClass(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClass(arg0, arg1, arg2);
            return result;
        }
    }
    async addScheduleEntry(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addScheduleEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScheduleEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteAnnouncement(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteAssignment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssignment(arg0);
            return result;
        }
    }
    async deleteClass(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0);
            return result;
        }
    }
    async deleteScheduleEntry(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduleEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduleEntry(arg0);
            return result;
        }
    }
    async getAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements();
            return result;
        }
    }
    async getAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignments();
            return result;
        }
    }
    async getAssignmentsByClass(arg0: string): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentsByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentsByClass(arg0);
            return result;
        }
    }
    async getAttendanceByClassAndDate(arg0: string, arg1: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByClassAndDate(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByClassAndDate(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByStudent(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByStudent(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByStudent(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassById(arg0: string): Promise<Class> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassById(arg0);
            return result;
        }
    }
    async getClasses(): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClasses();
            return result;
        }
    }
    async getClassesSortedById(): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassesSortedById();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassesSortedById();
            return result;
        }
    }
    async getGradesByAssignment(arg0: string): Promise<Array<Grade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradesByAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradesByAssignment(arg0);
            return result;
        }
    }
    async getGradesByStudent(arg0: string): Promise<Array<Grade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradesByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradesByStudent(arg0);
            return result;
        }
    }
    async getMessageThread(arg0: string, arg1: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageThread(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageThread(arg0, arg1);
            return result;
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getSchedule(): Promise<Array<ScheduleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchedule();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchedule();
            return result;
        }
    }
    async getScheduleByDay(arg0: bigint): Promise<Array<ScheduleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduleByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduleByDay(arg0);
            return result;
        }
    }
    async getStudentById(arg0: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentById(arg0);
            return result;
        }
    }
    async getStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudents();
            return result;
        }
    }
    async getStudentsByClass(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByClass(arg0);
            return result;
        }
    }
    async getUnreadCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount(arg0);
            return result;
        }
    }
    async markAttendance(arg0: string, arg1: string, arg2: string, arg3: AttendanceStatus): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, arg2, to_candid_AttendanceStatus_n6(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, arg2, to_candid_AttendanceStatus_n6(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async markMessageRead(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return result;
        }
    }
    async recordGrade(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGrade(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGrade(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async removeStudent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStudent(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateAssignment(arg0: Assignment): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssignment(arg0);
            return result;
        }
    }
    async updateAttendance(arg0: AttendanceRecord): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendance(to_candid_AttendanceRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendance(to_candid_AttendanceRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateClass(arg0: Class): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0);
            return result;
        }
    }
    async updateGrade(arg0: Grade): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGrade(arg0);
            return result;
        }
    }
    async updateScheduleEntry(arg0: ScheduleEntry): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScheduleEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScheduleEntry(arg0);
            return result;
        }
    }
    async updateStudent(arg0: Student): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0);
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AttendanceStatus;
    studentId: string;
    date: string;
    classId: string;
}): {
    id: string;
    status: AttendanceStatus;
    studentId: string;
    date: string;
    classId: string;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n4(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        classId: value.classId
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceRecord): _AttendanceRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: AttendanceStatus;
    studentId: string;
    date: string;
    classId: string;
}): {
    id: string;
    status: _AttendanceStatus;
    studentId: string;
    date: string;
    classId: string;
} {
    return {
        id: value.id,
        status: to_candid_AttendanceStatus_n6(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        classId: value.classId
    };
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.late ? {
        late: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
